stages:
  - testing

test-on-gnat-9:
  stage: testing
  image: 1maa/fsf-gnat:9
  before_script:
    - alr toolchain --disable-assistant
    - alr clean
    - gprbuild -j$(nproc) -Pexecutables
  script:
    - ./out/aunit_harness

test-on-gnat-10:
  stage: testing
  image: 1maa/fsf-gnat:10
  before_script:
    - alr toolchain --disable-assistant
    - alr clean
    - gprbuild -j$(nproc) -Pexecutables
  script:
    - ./out/aunit_harness
