stages:
  - build-check
  - testing

test-on-gnat-9:
  stage: testing
  image: 1maa/fsf-gnat:9
  before_script:
    - alr build -XRADATRACER_BUILD_MODE=optimize -XEXECUTABLES_BUILD_MODE=optimize
  script:
    - ./out/aunit_harness

test-on-gnat-10:
  stage: testing
  image: 1maa/fsf-gnat:10
  before_script:
    - alr build -XRADATRACER_BUILD_MODE=optimize -XEXECUTABLES_BUILD_MODE=optimize
  script:
    - ./out/aunit_harness
