stages:
  - build-check
  - testing

builds-on-gnat-9:
  stage: build-check
  image: 1maa/fsf-gnat:9
  script:
    - gprbuild -XRADATRACER_BUILD_MODE=optimize -XCAPSTONES_BUILD_MODE=optimize bin/capstones.gpr

builds-on-gnat-10:
  stage: build-check
  image: 1maa/fsf-gnat:10
  script:
    - gprbuild -XRADATRACER_BUILD_MODE=optimize -XCAPSTONES_BUILD_MODE=optimize bin/capstones.gpr

test-on-gnat-9:
  stage: testing
  needs:
    - builds-on-gnat-9
  image: 1maa/fsf-gnat:9
  before_script:
    - cd tests
    - alr build -XRADATRACER_BUILD_MODE=optimize -XTESTS_BUILD_MODE=optimize
  script:
    - ./out/harness

test-on-gnat-10:
  stage: testing
  needs:
    - builds-on-gnat-10
  image: 1maa/fsf-gnat:10
  before_script:
    - cd tests
    - alr build -XRADATRACER_BUILD_MODE=optimize -XTESTS_BUILD_MODE=optimize
  script:
    - ./out/harness
