name = "testradatracer"
description = "Shiny new project"
version = "0.0.0"

authors = ["Marcel Hernandez"]
maintainers = ["Marcel Hernandez <e6990620@gmail.com>"]
maintainers-logins = ["1ma"]

executables = ["testradatracer"]

[[depends-on]]
aunit = "^21.0.0"
